name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # This step sets up Node.js for your project
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # This step installs dependencies and builds your app
      - name: Install dependencies and build
        run: |
          cd app/frontend
          npm install
          npm run build
        
      # This step uploads the contents of the 'dist' folder (created by the build)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './app/frontend/dist'

  # This job handles the deployment
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
